day 07: try to factor out generic operator eval
Since Rust doesn't yet have generators, I am stuck here writing my own
state machine for this.

And I got some pretty good compiler spew:

	error[E0507]: cannot move out of `state.0`, as `state` is a captured variable in an `FnMut` closure
	   --> day_07/src/lib.rs:118:38
		|
	111 |     let state;
		|         ----- captured outer variable
	...
	118 |     std::iter::from_fn(move || match state {
		|                        -------       ^^^^^
		|                        |
		|                        captured by this `FnMut` closure
	...
	124 |         State::PassingDown(mut it) => match it.next() {
		|                            ------
		|                            |
		|                            data moved here
		|                            move occurs because `it` has type `std::boxed::Box<dyn std::iter::Iterator<Item = i64>>`, which does not implement the `Copy` trait
		|
	help: consider borrowing here
		|
	118 |     std::iter::from_fn(move || match &state {
		|                                      +

	error[E0594]: cannot assign to `state`, as it is not declared as mutable
	   --> day_07/src/lib.rs:121:13
		|
	111 |     let state;
		|         ----- help: consider changing this to be mutable: `mut state`
	...
	121 |             state = State::Done;
		|             ^^^^^ cannot assign

	error[E0594]: cannot assign to `state`, as it is not declared as mutable
	   --> day_07/src/lib.rs:128:21
		|
	111 |     let state;
		|         ----- help: consider changing this to be mutable: `mut state`
	...
	128 |                     state = State::Done;
		|                     ^^^^^ cannot assign

	error[E0700]: hidden type for `impl std::iter::Iterator<Item = i64>` captures lifetime that does not appear in bounds
	   --> day_07/src/lib.rs:118:5
		|
	103 |       mut operators: &[fn(i64, i64) -> i64],
		|                      ---------------------- hidden type `std::iter::FromFn<{closure@day_07/src/lib.rs:118:24: 118:31}>` captures the anonymous lifetime defined here
	104 |   ) -> impl Iterator<Item = i64> {
		|        ------------------------- opaque type defined here
	...
	118 | /     std::iter::from_fn(move || match state {
	119 | |         State::Done => None,
	120 | |         State::One(i) => {
	121 | |             state = State::Done;
	...   |
	138 | |         },
	139 | |     })
		| |______^
		|
	help: to declare that `impl std::iter::Iterator<Item = i64>` captures `'_`, you can introduce a named lifetime parameter `'a`
		|
	100 ~ fn all_options<'a>(
	101 |     first: i64,
	102 ~     rest: &'a [i64],
	103 ~     mut operators: &'a [fn(i64, i64) -> i64],
	104 ~ ) -> impl Iterator<Item = i64> + 'a  {
		|

	error[E0308]: mismatched types
	   --> day_07/src/lib.rs:42:69
		|
	42  |             for accumulator in all_options(values[0], &values[1..], [|a, b| a + b, |a, b| a * b]) {
		|                                -----------                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&[fn(i64, i64) -> i64]`, found `[fn(_, _) -> _; 2]`
		|                                |
		|                                arguments to this function are incorrect
		|
		= note: expected reference `&[fn(i64, i64) -> i64]`
					   found array `[fn(_, _) -> _; 2]`
	note: function defined here
	   --> day_07/src/lib.rs:100:4
		|
	100 | fn all_options(
		|    ^^^^^^^^^^^
	...
	103 |     mut operators: &[fn(i64, i64) -> i64],
		|     -------------------------------------
	help: consider borrowing here
		|
	42  |             for accumulator in all_options(values[0], &values[1..], &[|a, b| a + b, |a, b| a * b]) {
		|                                                                     +

	Some errors have detailed explanations: E0308, E0507, E0594, E0700.
	For more information about an error, try `rustc --explain E0308`.
	error: could not compile `day_07` (lib) due to 5 previous errors