day 07: more work on the refactor
Fewer errors ... I haven't even tried to decipher

	error[E0507]: cannot move out of `state.0`, as `state` is a captured variable in an `FnMut` closure
	   --> day_07/src/lib.rs:120:38
	    |
	111 |     let mut state;
	    |         --------- captured outer variable
	...
	120 |     std::iter::from_fn(move || match state {
	    |                        -------       ^^^^^
	    |                        |
	    |                        captured by this `FnMut` closure
	...
	126 |         State::PassingDown(mut it) => match it.next() {
	    |                            ------
	    |                            |
	    |                            data moved here
	    |                            move occurs because `it` has type `std::boxed::Box<dyn std::iter::Iterator<Item = i64>>`, which does not implement the `Copy` trait
	    |
	help: consider borrowing here
	    |
	120 |     std::iter::from_fn(move || match &state {
	    |                                      +

But this one is going to be even harder -- I don't know how to indicate
to rustc that the Box will not outlive 'a.

	error: lifetime may not live long enough
	   --> day_07/src/lib.rs:142:44
	    |
	100 | fn all_options<'a>(
	    |                -- lifetime `'a` defined here
	...
	142 |                 state = State::PassingDown(Box::new(new_it));
	    |                                            ^^^^^^^^^^^^^^^^ cast requires that `'a` must outlive `'static`

	For more information about this error, try `rustc --explain E0507`.